# Generated by Django 3.2 on 2024-09-01 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboProvisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dni', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('ruc', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)])),
                ('direccion', models.CharField(max_length=255)),
                ('telefono_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_celular', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('local', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=255)),
                ('area', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uso_exclusivo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('renta_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garantia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_adelantado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_alquiler', models.IntegerField()),
                ('total_recibo_provisional', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField()),
                ('mantenimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suministro_luz', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
            ],
        ),
    ]
